name: berksports
description: "Sports, Lifestyle & Activities"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  provider:
  path_provider:
  share_plus:
  #kotlin-bom: ^1.5.31  


dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter_launcher_icons:
  android: true  # Added android: true to generate launcher icons for Android
  ios: true
  image_path: assets/images/logo.png
  min_sdk_android: 26

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_breed.png
